version: '3.9'

networks:
  k6-support: {}

volumes:
  prometheus_data: {}
  grafana_data: {}
  influxdb_data: {}

services:
  telegraf:
    image: telegraf:1.22
    container_name: k6-support-telegraf
    volumes:
    - ./config/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '127.0.0.1:8125:8125/udp'
    networks:
      - k6-support

  prometheus:
    image: prom/prometheus:latest
    container_name: k6-support-prometheus
    restart: unless-stopped
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
    ports:
      - 9199:9090
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - k6-support

  influxdb:
    image: influxdb:1.8
    container_name: k6-support-influxdb
    restart: unless-stopped
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_USER=k6
      - INFLUXDB_USER_PASSWORD=k6
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
    volumes:
      - ./config/influxdb.conf:/etc/influxdb/influxdb.conf
      - influxdb_data:/var/lib/influxdb
    ports:
      - 8186:8086
    networks:
      - k6-support

  grafana:
    image: grafana/grafana-oss:latest
    container_name: k6-support-grafana
    restart: unless-stopped
    ports:
      - 9409:3000
    volumes:
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - k6-support

  node-exporter:
    image: prom/node-exporter:latest
    container_name: k6-support-node-exporter
    restart: unless-stopped
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - k6-support
    ports:
      - 9100:9100