{
 "title": "CloudFlare Public Analytics elhacker.NET",
 "description": "Last 12 hours - Updates every 5 minutes",
 "tags": [
  "public",
  "Cloudflare"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Eventos-Hits Reglas Firewall - WAF",
   "type": "bargauge",
   "description": "WAF - Web Application Firewall",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(rule) (cloudflare_zone_firewall_events_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Eventos WAF",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(source) (cloudflare_zone_firewall_events_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Country",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_country{zone='elhacker.net'}",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Browsers by family",
   "type": "piechart",
   "description": "Family browsers excluding search Bots",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_browser_map_page_views_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests / country",
   "type": "geomap",
   "description": "All requests excluding bots from USA and Singapur (TikTok)",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_country{zone=~\"elhacker.net\"}",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Requests Status Codes",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_status{zone='elhacker.net'}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Request Content Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_content_type{zone='elhacker.net'}",
     "legendFormat": "{{content_type}}"
    }
   ]
  },
  {
   "title": "Requests / Second (status codes not 2XX)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_status{zone='elhacker.net', status!~\"2..\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Threats / country",
   "type": "geomap",
   "description": "HeatMap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cloudflare_zone_threats_country{zone=\"elhacker.net\"}",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Requests / second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_total{zone=~\"elhacker.net\"}[10m])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(cloudflare_zone_requests_cached{zone=~\"elhacker.net\"}[10m])",
     "legendFormat": "cached"
    }
   ]
  },
  {
   "title": "SearchBots",
   "type": "piechart",
   "description": "Search Bots %",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_browser_map_page_views_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}