{
 "title": "System Metrics",
 "description": "System Metrics",
 "tags": [
  "system",
  "telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU metrics",
   "type": "timeseries",
   "description": "CPU metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "system_load1", "legendFormat": "1min" },
    { "expr": "system_load5", "legendFormat": "5min" },
    { "expr": "system_load15", "legendFormat": "15min" }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "description": "System Memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "mem_total", "legendFormat": "mem_total" },
    { "expr": "mem_available", "legendFormat": "mem_available" },
    { "expr": "mem_used", "legendFormat": "mem_used" },
    { "expr": "mem_free", "legendFormat": "mem_free" },
    { "expr": "mem_committed_as", "legendFormat": "mem_committed_as" }
   ]
  },
  {
   "title": "Docker CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Docker Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "docker_container_mem_usage", "legendFormat": "{{container_name}}" }
   ]
  },
  {
   "title": "Prometheus Query Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "Prometheus Query Samples Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "prometheus_engine_query_samples_total",
     "legendFormat": "prometheus_query_samples_total"
    }
   ]
  },
  {
   "title": "Disk IO metrics",
   "type": "timeseries",
   "description": "Disk IO metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "diskio_reads{name!=\"loop0\"} >= 500",
     "legendFormat": "{{name}} reads"
    },
    {
     "expr": "diskio_writes{name!=\"loop0\"} >= 500",
     "legendFormat": "{{name}} writes"
    }
   ]
  }
 ]
}