{
 "title": "InfluxDB Internals",
 "description": "InfluxDB internal metrics display",
 "tags": [
  "influxdb",
  "internal",
  "metrics"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "InfluxDB Metric Database", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "OVERVIEW",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "InfluxDB Active Queries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "queryExecutor",
     "select": [
      [
       { "params": [ "queriesActive" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "6f2024b72f0d" }
     ]
    }
   ]
  },
  {
   "title": "Average Query Duration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queryExecutor",
     "select": [
      [
       { "params": [ "queryDurationNs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "InfluxDB Data Caching Composition",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tsm1_cache",
     "select": [
      [
       { "params": [ "diskBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "diskBytes" ], "type": "alias" }
      ],
      [
       { "params": [ "memBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "memBytes" ], "type": "alias" }
      ],
      [
       { "params": [ "cachedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cachedBytes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "6f2024b72f0d" }
     ]
    }
   ]
  },
  {
   "title": "InfluxDB Heap Usage : stats-node-0",
   "type": "graph",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "bytes", "label": "MB" }
   ],
   "targets": [
    {
     "alias": "influx-0 $col",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "HeapInUse" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "heap active" ], "type": "alias" }
      ],
      [
       { "params": [ "HeapIdle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "heap idle" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "6f2024b72f0d" }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"queryReq\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Client Errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"clientError\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Server Errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"serverError\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DATABASE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Point Intake",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Write Fail",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"pointsWrittenFail\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Write OK",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"pointsWrittenOK\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measurement Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"numMeasurements\") FROM \"database\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Series Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"numSeries\") FROM \"database\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}