{
 "title": "InfluxDB 2.x Internal Basics",
 "description": "InfluxDB 2.x Internal Metrics Explorer",
 "tags": [
  "influxdb",
  "internal"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "bucket",
    "query": "buckets()\n  |> keep(columns: [\"name\"])\n  |> rename(columns: {name: \"_value\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Buckets",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "buckets()\n  |> rename(columns: {name: \"Database\"})\n  |> keep(columns: [\"Database\"])"
    }
   ]
  },
  {
   "title": "Measurements",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/v1\"\nv1.measurements(bucket: v.bucket)"
    }
   ]
  },
  {
   "title": "Field Keys",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.fieldKeys(bucket: v.bucket)"
    }
   ]
  }
 ]
}