{
 "title": "InfluxDB Overview",
 "description": "A beautiful one-stop-shop dashboard to monitor ALL your Influx instances. Both Influx specific metrics, as well key OS metrics.",
 "tags": [ "influxdb" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "InfluxDB Metric Database", "query": "influxdb" },
   {
    "name": "hostname",
    "query": "show tag values with key=\"hostname\""
   },
   {
    "name": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "### This dashboard aims to provide detailed visibility into the runtime stats for an InfluxDB instance using Influx's own metrics db - *_internal*, as well as a quick OS overview using *telegraf*. \n\nSimply chose the instance you want to monitor with the dropdown: \"InfluxDB Metric Database\". This dashboard also hosts all the **alerts** related to InfluxDB monitoring. \n\n> Please only add alerts to the row titled \"Alerts\", everything other than this row uses Grafana's Template variables in the panels, which does not support alerting.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "cpu_percentageBusy",
     "query": "SELECT 100-mean(usage_idle) as \"used\" FROM \"cpu\" WHERE \"host\" =~ /nj-mon/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"used_percent\") FROM \"mem\" WHERE (\"host\" =~ /^nj-mon/) AND $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O time for /dev/sda",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /nj-mon/ AND \"name\" =~ /sda$/  AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Queries",
   "type": "stat",
   "description": "Displays the number of HTTP requests per minute.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"queriesActive\" FROM \"monitor\".\"queryExecutor\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"hostname\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Write Request Duration (99th %)",
   "type": "stat",
   "description": "Displays the duration, in nanoseconds, of the top 1% of HTTP WRITE requests.",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Write Request {host: $tag_hostname}",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(percentile(\"writeReqDurationNs\", 99)) / non_negative_derivative(max(\"writeReq\")) AS \"Write Request\"\nFROM \"monitor\".\"httpd\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "writeReqDurationNs" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Read Request Duration (99th %)",
   "type": "stat",
   "description": "Displays the duration, in nanoseconds, of the top 1% of HTTP READ requests.",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Query Request {host: $tag_hostname}",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(percentile(\"queryReqDurationNs\", 99)) / non_negative_derivative(max(\"queryReq\")) AS \"Query Request\"\nFROM \"monitor\".\"httpd\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "writeReqDurationNs" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Host Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"uptime\") AS \"value\" FROM \"system\" WHERE \"host\" =~ /$hostname$/ AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"usage_idle\") * -1 + 100 FROM \"cpu\" WHERE (\"host\" =~ /^$hostname$/ AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"used_percent\") FROM \"mem\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nSELECT mean(\"usage_iowait\") FROM \"cpu\" WHERE (\"host\" =~ /^$hostname$/ AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "mem_inactive",
     "query": "SELECT mean(total) as total, mean(used) as used, mean(cached) as cached, mean(free) as free, mean(buffered) as buffered  FROM \"mem\" WHERE host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "cpu_percentageBusy",
     "query": "SELECT mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE \"host\" =~ /$hostname$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(bytes_recv),1s)*8 as \"in\"  FROM \"net\" WHERE host =~ /$hostname/  AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_interface: $col",
     "function": "derivative",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "interface", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "net_bytes_recv",
     "query": "SELECT non_negative_derivative(mean(bytes_sent),1s)*8 as \"out\" FROM \"net\" WHERE host =~ /$hostname/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "graph",
   "description": "Displays the current heap size.",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "query": "SELECT moving_average(mean(\"HeapSys\"), 10) AS \"heap sys\", moving_average(mean(\"HeapInUse\"), 10) AS \"heap active\", moving_average(mean(\"HeapIdle\"), 10) AS \"heap idle\" FROM \"monitor\".\"runtime\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"hostname\" fill(none)",
     "select": [
      [
       { "params": [ "HeapInUse" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "GC Activity",
   "type": "graph",
   "description": "Displays the current GC activity.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 25 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "query": "SELECT non_negative_derivative(mean(\"PauseTotalNs\"),1s) AS \"mean_PauseTotalNs\" FROM \"monitor\".\"runtime\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"hostname\" fill(none)",
     "select": [
      [
       { "params": [ "HeapInUse" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O time for /dev/sda",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$hostname$/ AND \"name\" =~ /sda$/  AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(write_time),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$hostname$/ AND \"name\" =~ /sda$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Httpd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP Requests / Minute",
   "type": "timeseries",
   "description": "Displays the number of HTTP requests per minute.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Query {host: $tag_hostname}",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(mean(\"queryReq\"), 1m) FROM \"monitor\".\"httpd\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "queryReq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Write {host: $tag_hostname}",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "select": [
      [
       { "params": [ "writeReq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Errors / Minute",
   "type": "timeseries",
   "description": "Displays the number of HTTP errors per minute.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Server Errors {host: $tag_hostname}",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "select": [
      [
       { "params": [ "serverError" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Client Errors {host: $tag_hostname}",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "select": [
      [
       { "params": [ "clientError" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Request Duration (99th %)",
   "type": "timeseries",
   "description": "Displays the duration, in nanoseconds, of the top 1% of HTTP requests.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Write Request {host: $tag_hostname}",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(percentile(\"writeReqDurationNs\", 99)) / non_negative_derivative(max(\"writeReq\")) AS \"Write Request\"\nFROM \"monitor\".\"httpd\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "writeReqDurationNs" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "Query Request {host: $tag_hostname}",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(percentile(\"queryReqDurationNs\", 99)) / non_negative_derivative(max(\"queryReq\")) AS \"Query Request\"\nFROM \"monitor\".\"httpd\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "writeReqDurationNs" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests / Secs",
   "type": "timeseries",
   "description": "Displays the number of HTTP requests per seconds",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Query {host: $tag_hostname}",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(mean(\"queryReq\"), 1m) FROM \"monitor\".\"httpd\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($Interval), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "queryReq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Write {host: $tag_hostname}",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "select": [
      [
       { "params": [ "writeReq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Errors / Secs",
   "type": "timeseries",
   "description": "Displays the number of HTTP errors per seconds.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Server Errors {host: $tag_hostname}",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "select": [
      [
       { "params": [ "serverError" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Client Errors {host: $tag_hostname}",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "select": [
      [
       { "params": [ "clientError" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Db - Shards/DBs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Measurements by Database",
   "type": "graph",
   "description": "Displays the number of measurements, by database.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_database",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "database",
     "select": [
      [
       { "params": [ "numMeasurements" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Series Cardinality by Database",
   "type": "graph",
   "description": "Displays the number of series (series cardinality) for the specified databases.",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_database",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "database",
     "select": [
      [
       { "params": [ "numSeries" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shard Write Errors",
   "type": "timeseries",
   "description": "Displays the number of shard write errors.",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "{host: $tag_hostname}",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "write",
     "select": [
      [
       { "params": [ "writeError" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Continuous Queries Executed / Minute",
   "type": "timeseries",
   "description": "Displays the non-negative mean rate of change in continuous queries (CQs) executed per minute.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Query OK",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cq",
     "select": [
      [
       { "params": [ "queryOk" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Query Fail",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cq",
     "select": [
      [
       { "params": [ "queryFail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queries Executed / Minute",
   "type": "timeseries",
   "description": "Displays the number of queries executed per minute.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "{host: $tag_hostname}",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queryExecutor",
     "select": [
      [
       { "params": [ "queriesExecuted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Point Throughput / Minute by Hostname",
   "type": "timeseries",
   "description": "Displays the number of points requested each minute, by hostname.",
   "gridPos": { "h": 9, "w": 7, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "{host: $tag_hostname}",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "write",
     "select": [
      [
       { "params": [ "pointReq" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Point Ingest Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "alias": "Write Fail",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"pointsWrittenFail\"), 1m) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Write OK",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"pointsWrittenOK\"), 1m) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queries Executed / Second",
   "type": "timeseries",
   "description": "Displays the number of queries executed per second.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "{host: $tag_hostname}",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queryExecutor",
     "select": [
      [
       { "params": [ "queriesExecuted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Point Throughput / Second by Hostname",
   "type": "timeseries",
   "description": "Displays the number of points requested each second, by hostname.",
   "gridPos": { "h": 9, "w": 7, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "{host: $tag_hostname}",
     "groupBy": [
      { "params": [ "$Interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "write",
     "select": [
      [
       { "params": [ "pointReq" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Point Ingest Rate /sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "Write Fail",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"pointsWrittenFail\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Write OK",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(last(\"pointsWrittenOK\"), 1s) FROM \"httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}