#!/bin/bash
# create additional influxdb users
INFLUXDB_INIT_PORT="8086"
INFLUXDB_ADMIN_USER="admin"
INFLUXDB_ADMIN_PASSWORD="password"
INFLUXDB_TELEGRAF_USER='telegraf'
INFLUXDB_TELEGRAF_PASSWORD='password'
INFLUXDB_K6_USER='k6'
INFLUXDB_K6_PASSWORD='k6'
INFLUXDB_DB_K6='k6'
INFLUXDB_DB_TELEGRAF='telegraf'

influx -host 127.0.0.1 -port $INFLUXDB_INIT_PORT \
       -execute "CREATE USER \"$INFLUXDB_ADMIN_USER\" WITH PASSWORD '$INFLUXDB_ADMIN_PASSWORD' WITH ALL PRIVILEGES"

influx -host 127.0.0.1 -port $INFLUXDB_INIT_PORT \
       -execute "CREATE USER \"$INFLUXDB_TELEGRAF_USER\" WITH PASSWORD '$INFLUXDB_TELEGRAF_PASSWORD'"

influx -host 127.0.0.1 -port $INFLUXDB_INIT_PORT \
       -execute "CREATE USER \"$INFLUXDB_K6_USER\" WITH PASSWORD '$INFLUXDB_K6_PASSWORD'"

influx -host 127.0.0.1 -port $INFLUXDB_INIT_PORT \
       -execute "CREATE DATABASE $INFLUXDB_DB_K6"

influx -host 127.0.0.1 -port $INFLUXDB_INIT_PORT \
       -execute "CREATE DATABASE $INFLUXDB_DB_TELEGRAF"


      