#!/bin/bash
# create additional influxdb users
INFLUXDB_INIT_PORT="8086"
INFLUXDB_ADMIN_USER="admin"
INFLUXDB_ADMIN_PASSWORD="password"
INFLUXDB_TELEGRAF_USER='telegraf'
INFLUXDB_TELEGRAF_PASSWORD='password'
INFLUXDB_K6_USER='k6'
INFLUXDB_K6_PASSWORD='k6'
INFLUXDB_PSRECORD_USER='psrecord'
INFLUXDB_PSRECORD_PASSWORD='password'
INFLUXDB_DB_K6='k6'
INFLUXDB_DB_TELEGRAF='telegraf'
INFLUXDB_DB_PSRECORD='psrecord'

influx -host 127.0.0.1 -port $INFLUXDB_INIT_PORT \
       -execute "CREATE USER \"$INFLUXDB_ADMIN_USER\" WITH PASSWORD '$INFLUXDB_ADMIN_PASSWORD' WITH ALL PRIVILEGES"

INFLUX_CMD="influx -host 127.0.0.1 -port $INFLUXDB_INIT_PORT -username ${INFLUXDB_ADMIN_USER} -password ${INFLUXDB_ADMIN_PASSWORD} -execute "

$INFLUX_CMD "CREATE USER \"$INFLUXDB_TELEGRAF_USER\" WITH PASSWORD '$INFLUXDB_TELEGRAF_PASSWORD'"
$INFLUX_CMD "CREATE USER \"$INFLUXDB_K6_USER\" WITH PASSWORD '$INFLUXDB_K6_PASSWORD'"
$INFLUX_CMD "CREATE USER \"$INFLUXDB_PSRECORD_USER\" WITH PASSWORD '$INFLUXDB_PSRECORD_PASSWORD'"

$INFLUX_CMD "CREATE DATABASE $INFLUXDB_DB_K6"
$INFLUX_CMD "CREATE DATABASE $INFLUXDB_DB_TELEGRAF"
$INFLUX_CMD "CREATE DATABASE $INFLUXDB_DB_PSRECORD"

$INFLUX_CMD "REVOKE ALL PRIVILEGES FROM \"$INFLUXDB_K6_USER\""
$INFLUX_CMD "GRANT ALL ON \"$INFLUXDB_DB_K6\" TO \"$INFLUXDB_K6_USER\""

$INFLUX_CMD "REVOKE ALL PRIVILEGES FROM \"$INFLUXDB_TELEGRAF_USER\""
$INFLUX_CMD "GRANT ALL ON \"$INFLUXDB_DB_TELEGRAF\" TO \"$INFLUXDB_TELEGRAF_USER\""

$INFLUX_CMD "REVOKE ALL PRIVILEGES FROM \"$INFLUXDB_PSRECORD_USER\""
$INFLUX_CMD "GRANT ALL ON \"$INFLUXDB_DB_PSRECORD\" TO \"$INFLUXDB_PSRECORD_USER\""