{
 "title": "Cloudflare R2 Analytics",
 "description": "Analytics about R2 Storage",
 "tags": [ "cloudflare" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account",
    "label": "Cloudflare Account",
    "query": {
     "query": "label_values(cloudflare_r2_storage_bytes,account)"
    }
   },
   {
    "name": "bucket",
    "label": "Cloudflare R2 Bucket",
    "query": {
     "query": "label_values(cloudflare_r2_operation_count,bucket)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Operation Count",
   "type": "piechart",
   "description": "Total Amounts of R2 operations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cloudflare_r2_operation_count) by (operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloudflare R2 Operations",
   "type": "timeseries",
   "description": "Cloudflare R2 Operations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(bucket, operation) (cloudflare_r2_operation_count)",
     "legendFormat": "{{bucket}}-{{operation}}"
    }
   ]
  },
  {
   "title": "Total R2 Storage",
   "type": "timeseries",
   "description": "Total Amount of Storage used by R2",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(cloudflare_r2_storage_bytes) by (account)",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "R2 Storage by Bucket",
   "type": "timeseries",
   "description": "Storage used by each bucket",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(cloudflare_r2_storage_bytes) by (bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloudflare R2 Operations",
   "type": "timeseries",
   "description": "Cloudflare R2 Operations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(operation) (cloudflare_prometheus_cloudflare_r2_operation_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bucket - $bucket",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "repeat": "bucket",
   "collapsed": true,
   "panels": [
    {
     "title": "Operation Count",
     "type": "piechart",
     "description": "Total Amounts of R2 operations.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cloudflare_r2_operation_count{bucket=~\"$bucket\"}) by (operation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage",
     "type": "timeseries",
     "description": "Amount of Storage used by R2",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "cloudflare_r2_storage_bytes{bucket=~\"$bucket\"}",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  }
 ]
}