{
 "title": "Cloudflare Workers v1",
 "description": "Cloudflare Workers v1",
 "tags": [ "cloudflare" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Cloudflare Workers CPU Time Avg (ms)",
   "type": "timeseries",
   "description": "Cloudflare Workers CPU Time Avg (ms)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_prometheus_cloudflare_worker_cpu_time[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloudflare Workers Duration GB-sec",
   "type": "timeseries",
   "description": "Cloudflare Workers Duration GB-sec",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_prometheus_cloudflare_worker_duration[1m]))",
     "legendFormat": "cpu worker duration GB-sec"
    }
   ]
  },
  {
   "title": "Cloudflare Workers req/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_prometheus_cloudflare_worker_requests_count[$__rate_interval]))",
     "legendFormat": "Workers req/min"
    }
   ]
  },
  {
   "title": "Cloudflare Workers Errors req/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_prometheus_cloudflare_worker_errors_count[$__rate_interval]))",
     "legendFormat": "Workers Errors req/min"
    }
   ]
  },
  {
   "title": "Cloudflare Workers Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(account) (cloudflare_prometheus_cloudflare_worker_requests_count)",
     "legendFormat": "Worker Requests"
    }
   ]
  },
  {
   "title": "Cloudflare Workers Total Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(account) (cloudflare_prometheus_cloudflare_worker_errors_count)",
     "legendFormat": "Worker Errors"
    }
   ]
  },
  {
   "title": "Cloudflare Workers Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "cloudflare_worker_requests_count",
     "legendFormat": "{{script_name}}"
    }
   ]
  },
  {
   "title": "Cloudflare Workers Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(cloudflare_prometheus_cloudflare_worker_errors_count[$__rate_interval])",
     "legendFormat": "{{script_name}}"
    }
   ]
  },
  {
   "title": "Cloudflare Workers CPU Time (ms) <30ms P50",
   "type": "barchart",
   "description": "Cloudflare Workers CPU Time (ms) <30ms P50",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "cloudflare_prometheus_cloudflare_worker_cpu_time{quantile=\"P50\"} <= 30000",
     "legendFormat": "p50-{{script_name}}"
    }
   ]
  },
  {
   "title": "Cloudflare Workers CPU Time (ms) <30ms P99",
   "type": "barchart",
   "description": "Cloudflare Workers CPU Time (ms) <30ms P99",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "cloudflare_prometheus_cloudflare_worker_cpu_time{quantile=\"P99\"} <= 30000",
     "legendFormat": "p99-{{script_name}}"
    }
   ]
  },
  {
   "title": "Cloudflare Workers CPU Time (ms) >30ms P50",
   "type": "barchart",
   "description": "Cloudflare Workers CPU Time (ms) >30ms P50",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "cloudflare_prometheus_cloudflare_worker_cpu_time{quantile=\"P50\"} >= 30000",
     "legendFormat": "p50-{{script_name}}"
    }
   ]
  },
  {
   "title": "Cloudflare Worker Duration GB-sec",
   "type": "timeseries",
   "description": "Cloudflare Worker Duration GB-sec",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "cloudflare_worker_duration{quantile=\"P50\"} > 0.005",
     "legendFormat": "p50-{{script_name}}"
    }
   ]
  }
 ]
}