{
 "title": "Cloudflared Tunnel Metrics",
 "description": "Cloudflared Tunnel Metrics",
 "tags": [ "cloudflare" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Cloudflared Tunnel Total Requests",
   "type": "timeseries",
   "description": "Cloudflared Tunnel Total Requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cloudflared_tunnel_total_requests",
     "legendFormat": "grafana tunnel"
    }
   ]
  },
  {
   "title": "Cloudflared Tunnel Request Errors",
   "type": "timeseries",
   "description": "Cloudflared Tunnel Request Errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "cloudflared_tunnel_request_errors",
     "legendFormat": "grafana tunnel"
    }
   ]
  },
  {
   "title": "Cloudflared Tunnel Server Locations",
   "type": "timeseries",
   "description": "Cloudflared Tunnel Server Locations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "cloudflared_tunnel_server_locations",
     "legendFormat": "{{edge_location}}"
    }
   ]
  },
  {
   "title": "Cloudflared Tunnel Response By Status Code",
   "type": "timeseries",
   "description": "Cloudflared Tunnel Response By Status Code",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "cloudflared_tunnel_response_by_code",
     "legendFormat": "{{status_code}}"
    }
   ]
  }
 ]
}