{
 "title": "CloudFlare Public Analytics",
 "description": "Last 12 hours - Updates every 5 minutes",
 "tags": [
  "public",
  "cloudflare"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Event Hits WAF Firewall",
   "type": "bargauge",
   "description": "Event Hits WAF Firewall",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(rule) (cloudflare_zone_firewall_events_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests By Country",
   "type": "piechart",
   "description": "Requests By Country",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_country",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "WAF Events By Hostname",
   "type": "timeseries",
   "description": "WAF Events By Hostname",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "topk(25, sum by(host) (cloudflare_prometheus_cloudflare_zone_firewall_events_count))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAF Actions By Country (exclude LOG action)",
   "type": "timeseries",
   "description": "WAF Actions By Country (exclude LOG action)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "topk by(country, action) (25, cloudflare_prometheus_cloudflare_zone_firewall_events_count{action!=\"log\"})",
     "legendFormat": "{{country}}-{{action}}"
    }
   ]
  },
  {
   "title": "WAF Events By Country",
   "type": "timeseries",
   "description": "WAF Events By Country",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "topk(20, sum by(country) (cloudflare_prometheus_cloudflare_zone_firewall_events_count))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Traffic By Edge Colo",
   "type": "timeseries",
   "description": "HTTP Traffic By Edge Colo",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "topk(25, sum by(colocation) (cloudflare_prometheus_cloudflare_zone_colocation_requests_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAF Events By Action",
   "type": "timeseries",
   "description": "WAF Events By Action",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk(20, sum by(action) (cloudflare_prometheus_cloudflare_zone_firewall_events_count))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests By Status",
   "type": "timeseries",
   "description": "HTTP Requests By Status",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "topk(20, cloudflare_prometheus_cloudflare_zone_requests_status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "WAF Events By Classification",
   "type": "timeseries",
   "description": "WAF Events By Classification",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by(source) (cloudflare_prometheus_cloudflare_zone_firewall_events_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests By Host Country Status",
   "type": "timeseries",
   "description": "HTTP Requests By Host Country Status",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_status_country_host",
     "legendFormat": "{{host}}-{{country}}-{{status}}"
    }
   ]
  },
  {
   "title": "Requests / second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_total[10m])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(cloudflare_zone_requests_cached{zone=~\"elhacker.net\"}[10m])",
     "legendFormat": "cached"
    }
   ]
  },
  {
   "title": "SearchBots Extended",
   "type": "piechart",
   "description": "Search Bots %",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_browser_map_page_views_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests / Second (status codes not 2XX)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_status{status!~\"2..\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "SearchBots",
   "type": "piechart",
   "description": "Search Bots %",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_browser_map_page_views_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_status",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Requests / country",
   "type": "geomap",
   "description": "All requests",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_country",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Request Content Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_content_type",
     "legendFormat": "{{content_type}}"
    }
   ]
  },
  {
   "title": "Threats / country",
   "type": "geomap",
   "description": "HeatMap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cloudflare_zone_threats_country",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Browsers",
   "type": "piechart",
   "description": "Family browsers excluding search Bots",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_browser_map_page_views_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}