{
 "title": "Cloudflare WAF Firewall Metrics",
 "tags": [ "cloudflare" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Cloudflare WAF Firewall Actions",
   "type": "stat",
   "description": "Cloudflare WAF Firewall Actions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(action) (cloudflare_zone_firewall_events_count)",
     "legendFormat": "{{action}}-avg"
    },
    {
     "expr": "max by(action) (cloudflare_zone_firewall_events_count)",
     "legendFormat": "{{action}}-max"
    }
   ]
  },
  {
   "title": "Cloudflare WAF Firewall Actions Rate/sec",
   "type": "stat",
   "description": "Cloudflare WAF Firewall Actions Rate/sec",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(action) (rate(cloudflare_zone_firewall_events_count[$__rate_interval]))",
     "legendFormat": "{{action}}-avg"
    },
    {
     "expr": "max by(action) (rate(cloudflare_zone_firewall_events_count[$__rate_interval]))",
     "legendFormat": "{{action}}-max"
    }
   ]
  },
  {
   "title": "Cloudflare Firewall Events (managed challenges)",
   "type": "timeseries",
   "description": "Cloudflare Firewall Events (managed challenges)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(action, host) (cloudflare_zone_firewall_events_count{action=\"managed_challenge\"})",
     "legendFormat": "{{action}}-{{host}}"
    },
    {
     "expr": "sum by(action, host) (cloudflare_zone_firewall_events_count{action=\"managed_challenge_bypassed\"})",
     "legendFormat": "{{action}}-{{host}}"
    }
   ]
  },
  {
   "title": "Cloudflare Firewall Events blocks (exclude LOG action)",
   "type": "timeseries",
   "description": "Cloudflare Firewall Events blocks (exclude LOG action)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(action, host) (cloudflare_zone_firewall_events_count{action=\"block\"})",
     "legendFormat": "{{action}}-{{host}}"
    }
   ]
  },
  {
   "title": "Cloudflare Firewall Events (skip)",
   "type": "timeseries",
   "description": "Cloudflare Firewall Events (skip)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(action, host) (cloudflare_zone_firewall_events_count{action=\"skip\"})",
     "legendFormat": "{{action}}-{{host}}"
    }
   ]
  },
  {
   "title": "Cloudflare Firewall Events (log)",
   "type": "timeseries",
   "description": "Cloudflare Firewall Events (log)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(action, host) (cloudflare_zone_firewall_events_count{action=\"log\"})",
     "legendFormat": "{{action}}-{{host}}"
    }
   ]
  }
 ]
}