apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: false
    version: 1
    jsonData:
      timeInterval: "30s"        # Minimum time interval between data points. Prevent too granular queries that could overload the system
      queryTimeout: "900s"       # Maximum time a query can run before timing out (10 minutes)
      httpMethod: "POST"         # Uses POST instead of GET for queries. Better for large queries as it avoids URL length limitations
      manageAlerts: true         # Allows Grafana to manage Prometheus alerts
      cacheLevel: "High"         # Maximizes caching of query results to improve performance
      disableRecordingRules: false  # Allows use of Prometheus recording rules which can pre-compute expensive queries
      incrementalQuerying: true     # Breaks large time-range queries into smaller chunks
      incrementalQueryOverlapWindow: "15m"  # When using incremental queries, adds 10m overlap between chunks to ensure continuity
      cacheMaxAge: "900s"      # How long to keep query results in cache (10 minutes)
      timeoutInSeconds: 900      # Explicit timeout setting
      queryTimeoutEnabled: true  # Enable query timeout

  - name: influxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: k6
      httpMode: GET
      v1Compatibility: true
      v1Database: k6
      v1User: k6
    secureJsonData:
      v1Password: k6
      token: ${INFLUX_TOKEN}
    isDefault: false
    editable: true
    version: 1

  - name: influxDB-telegraf
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: telegraf
      httpMode: GET
      v1Compatibility: true
      v1Database: telegraf
      v1User: telegraf
    secureJsonData:
      v1Password: password
      token: ${INFLUX_TOKEN}
    isDefault: false
    editable: true
    version: 1

  - name: influxDB-psrecord
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: psrecord
      httpMode: GET
      v1Compatibility: true
      v1Database: psrecord
      v1User: psrecord
    secureJsonData:
      v1Password: password
      token: ${INFLUX_TOKEN}
    isDefault: false
    editable: true
    version: 1

  - name: influxDB-internal-metrics
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: _internal
      httpMode: GET
      v1Compatibility: true
      v1Database: _internal
      v1User: admin
    secureJsonData:
      v1Password: password
      token: ${INFLUX_TOKEN}
    isDefault: false
    editable: true
    version: 1

  - name: influxDB-cloudflare
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: cloudflare
      httpMode: GET
      v1Compatibility: true
      v1Database: cloudflare
    secureJsonData:
      token: ${INFLUX_TOKEN}
    isDefault: false
    editable: true
    version: 1

  - name: Thanos
    type: prometheus
    access: proxy
    url: http://thanos-query:19192
    jsonData:
      timeInterval: "30s"